config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  
  get 'home/about' => 'homes#about'
  
  resources :users, only: [:show, :index, :edit, :update]
  resources :books, only: [:new, :create, :edit, :update, :index, :show, :destroy] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy] #単数にするとコントローラのidがリクエストに含まれなくなる
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists? #where(カラム名: 条件)
  end

  validates :title, presence: true
  validates :body, presence: true, length: {maximum:200}
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  
  belongs_to :user
  belongs_to :book
  
  validates :comment, presence: true #commentで空白が渡されたらエラーが
  
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :book
  belongs_to :user
  
  validates_uniqueness_of :book_id, scope: :user_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :books, dependent: :destroy
  attachment :profile_image
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  validates :name, uniqueness: true, length: {minimum: 2, maximum:20}
  validates :introduction, length: {maximum:50}
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except:[:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def after_sign_out_path_for(resource)
    root_path
  end
  
  def after_sign_in_path_for(resource)
	  user_path(current_user.id)
  end
  
  
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
  
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
   before_action :authenticate_user!

  def create
    @book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = @book.id
    comment.save
    redirect_back(fallback_location: root_url)
  end

  def destroy
    BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
    redirect_back(fallback_location: root_url)
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
    #ログインしているユーザのみ使用
  before_action :set_book, only: [:edit, :update]
  
  
  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @user = current_user
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render "edit"
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    @book.user_id = current_user.id
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render 'edit'
    end
  end

  def index
    @book = Book.new
    @books = Book.all
    @user = current_user
  
  end

  def show
    @new_book = Book.new
    @book = Book.find(params[:id]) #モデルと紐づいているデータベースのテーブルから、レコードを1つ取り出す場合に使用
    @user = @book.user
    @book_comment = BookComment.new
    @book_comments = @book.book_comments
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private
  
  def book_params
    params.require(:book).permit(:title, :body)
  end
  
  def set_book
      @book = Book.find(params[:id])
    unless @book.user.id == current_user.id
      redirect_to books_path
    end
  end
  
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    @favorite = current_user.favorites.new(book_id: @book.id)
    @favorite.save
    redirect_back(fallback_location: root_url)
  end
  
  def destroy
    @book = Book.find(params[:book_id])
    @favorite = current_user.favorites.find_by(book_id: @book.id)
    @favorite.destroy
    redirect_back(fallback_location: root_url)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    
  end
  
  def about
    
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:edit, :update]
 
  def index
    @user = current_user
    @users = User.all
    @book = Book.new
    @books = Book.all
  end
  
  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = Book.where(user_id: @user.id)
  end

  
  def edit
    @user = User.find(params[:id])
    if @user.id != current_user.id
      redirect_to user_path(current_user.id)
    end
  end
  
  
  def update
  	@user = User.find(params[:id])
  	@user.update(user_params)
  	if @user.save
  		redirect_to user_path(@user.id)
      flash[:notice] = "You have updated user successfully."
  	else
  		render :edit
  	end
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
  
  def set_user
    @user = User.find(params[:id])
    unless @user = current_user
      redirect_to user_path(current_user)
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/kaminaris_helper.rb
module KaminarisHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<div class="col-md-3">
<h2>User info</h2>
 <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg",size:'100x100' %>

  <table class="table">
		<tbody>
			<tr>
			  <th>name</th>
			  <th><%= user.name %></th>
		  </tr>
			<tr>
			  <th>introduction</th>
			  <th><%= user.introduction %></th>
		  </tr>
    </tbody>
  </table>
  <div class="row">
    <%= link_to '', edit_user_path(@user), class: "btn btn-outline-secondary btn-block fas fa-user-cog edit_user_#{current_user.id}" %>
  </div>
   

	 <h2 class="mt-3">New book</h2>
	 <%= form_with model: book, local:true do |f| %>
	   <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: "form-control book_title" %>
    </div>
    <div class="form-group">
      <%= f.label :opinion %>
      <%= f.text_area :body, class: "form-control book_body" %>
    </div>
    <div class="form-group">
      <%= f.submit "Create Book", class: "btn btn-success" %>
    </div>
  <% end %>
 </div>
 

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
      <% if @book.errors.any? %>
      <div id="errors_explanation">
      <h2><%= @book.errors.count %> errors prohibited this obj from being saved:</h2>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
      </div>
      <% end %>
      <%= form_with model: @book, local:true do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: "form-control book_title" %>
      </div>
      
      <div class="form-group">
        <%= f.label :opinion %>
        <%= f.text_area :body, class: "form-control book_body" %>
      </div>
      
      <div class="form-group">
        <%= f.submit "Update Book", class: "btn btn-success" %>
      </div>
      <% end %>
      <%= link_to "Show", book_path(@book.id) %> |
    
      <%= link_to "Back", books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
  <%if @book.errors.any? %>
    <div id="error_explanation">
      <h3><%= @book.errors.count %> error prohibited this obj from being saved:</h3>
      <ul>
      <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="row">
  <%= render 'books/list', user: @user, book: @book %>
    <div class="col-md-8 offset-md-1">
	<h2>Books</h2>
	  <table class="table table-hover table-inverse" >
	    <thead>
	    	<tr>
	    	  <th></th>
	    	  <th>Title</th>
	    	  <th>Opinion</th>
	    	  <th colspan="3"></th>
	    	</tr>
	    </thead>
	    <tbody>
        <% @books.each do |book| %>
	       	<tr>
	    	  <td>
            <%= link_to user_path(book.user.id) do %>
	    	  	<%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image_people.jpg", size:'40x40' %>
	    	  	<% end %>
	       	</td>
	        <td><%= link_to book.title, book_path(book.id) %></td>
	    	  <td><%= book.body %></td>
	    	  <td>
	    	      <% if book.favorited_by?(current_user) %> 
                  <%= link_to book_favorites_path(book.id), method: :delete do %>
                    <i class="fas fa-heart" aria-hidden="true" style="color: red;">
                    <%= book.favorites.count %></i>
                  <% end %>
                  <% else %>
                  <%= link_to book_favorites_path(book.id), method: :post do %>
                    <i class="fas fa-heart" aria-hidden="true">
                    <%= book.favorites.count %></i>
                  <% end %>
              <% end %>
            </td>
	    	  <td>コメント数:<%= book.book_comments.count %></td>
	    	  </tr>
	    	<% end %>
	    </tbody>
	  </table>
   </div>
</div>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <%= render 'books/list', user: @user, book: @new_book %>
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
        <table class="table">
          <tr>
            <td>
              <%= link_to user_path(@book.user_id) do %>
              <%= attachment_image_tag @book.user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image_people.jpg", size: '40x40' %><br />
              <%= @book.user.name %>
              <% end %>
            </td>
            <td>
              <%= link_to book_path(@book.id) do %>
              <%= @book.title %>
              <% end %>
            </td>
            <td>
              <%= @book.body %> 
            </td>
            <td>
              <% if @book.favorited_by?(current_user) %>
                  <%= link_to book_favorites_path(@book), method: :delete do %>
                    <i class="fas fa-heart" aria-hidden="true" style="color: red;">
                    <%= @book.favorites.count %></i>
                  <% end %>
                  <% else %>
                  <%= link_to book_favorites_path(@book), method: :post do %>
                    <i class="fas fa-heart" aria-hidden="true">
                    <%= @book.favorites.count %></i>
                  <% end %>
              <% end %>
            </td>
            <td>
              コメント数:<%= @book_comments.count %>
            </td>
            <% if @book.user == current_user %>
            
            <td><%= link_to "Edit", edit_book_path(@book), class:"btn btn-success"%></td>
            <td><%= link_to "Destroy", book_path(@book), method: :delete, data: {confirm: "本当に消しますか？"}, class:"btn btn-danger" %></td>
            <% end %>
          </tr>
        </table>
         
         
        <table class="table">
					<% @book_comments.each do |book_comment| %>
					<tr>
					<td>
						<%= attachment_image_tag book_comment.user, :profile_image, :fill, 50, 50, fallback: "no_image_people.jpg", size:'40×40' %> </br>
   					<%= book_comment.user.name %>	
					</td>
					<td>
						<%= book_comment.comment %>
            <% if book_comment.user_id == current_user.id %>
            <%= link_to "Destroy", book_book_comment_path(@book, book_comment.id), method: :delete, class:"btn btn-danger" %></td>
            <% end %>
          </td>
          </tr>
          <% end %>
        </table>
          
        
            <%= form_with(model:[@book, @book_comment], local: true) do |f| %>
            <div class = "form-group">
            <%= f.text_area :comment, class:'form-control input-sm' %>
            </div>
            <div class = "form-group">
            <%= f.submit "送信" %>
            </div>
            <% end %>
        
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i>
    <strong>Bookers</strong>!
    </h1>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
    <div class="row">
        <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
            <h1>
                welcome to
                <i class="fas fa-book"></i>
                <strong>Bookers</strong>
                  !!
            </h1>
            <p>
                In 
                <i class="fas fa-book"></i>
                <strong>Bookers</strong>,
            </p>
            <p>you can share and exchange your opinions, inpressions, and emotions</p>
            <p>about various books!</p>
            <div class="btn-wrapper col-10 mx-auto">
                <div class="row">
                    <%= link_to "Log in", new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign_in" %>
                </div>
                <div class="row">
                    <%= link_to "Sign up", new_user_registration_path, class: "btn btn-success btn-sm btn-block sign_up" %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/kaminaris/first_page.html.erb
<%# Link to the "First" page
  - available local variables
    url:           url to the first page
    current_page:  a page object for the currently displayed page
    total_pages:   total number of pages
    per_page:      number of items to fetch per page
    remote:        data-remote
-%>
<span class="first">
  <%= link_to_unless current_page.first?, t('views.pagination.first').html_safe, url, remote: remote %>
</span>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
     <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">
            <span>Bookers</span>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
              <li>
                <%= link_to "Home", user_path(current_user.id), class: 'fas fa-home nav-link text-light' %>
              </li>
              <li>
                <%= link_to "Users", users_path, class: 'fas fa-users nav-link text-light' %>
              </li>
              <li>
                <%= link_to "Books", books_path, class: 'fas fa-book-open nav-link text-light' %>
              </li>
              <li>
                <%= link_to "logout", destroy_user_session_path, method: :delete, class: 'fas fa-sign-out-alt nav-link text-light' %>
              </li>
              <% else %>
              <li>
                <%= link_to "Home", root_path, class: 'fas fa-home nav-link text-light' %>
              </li>
              <li>
                <%= link_to "About", home_about_path, class: 'fas fa-link nav-link text-light' %>
              </li>
              <li>
                <%= link_to "sign up", new_user_registration_path, class: 'fas fa-user-plus nav-link text-light' %>
              </li>
              <li>
                <%= link_to "login", new_user_session_path, class: 'fas fa-sign-in-alt nav-link text-light' %>
              </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    
    <main>
      <p id="notice">
        <%= flash[:notice] %>
      </p>
        <%= yield %>
    </main>
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<div class="container">
 <div class="row">
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
   <h2>User info</h2>
   <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= @user.errors.count %> errors prohibited this obj from being saved:</h2>
      <ul>
      <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
   <%= form_with model:@user, local:true do |f| %>
   <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control user_name" %>
   </div>
   <div class="form-group">
    <%= f.label :image %>
    <%= f.attachment_field :profile_image, class: "form-control-file user_image" %>
   </div>
   <div class="form-group">
    <%= f.label :introduction %>
    <%= f.text_area :introduction, class: "form-control user_introduction" %>
   </div>
   <div class="form-group">
    <%= f.submit "Update User", class: "btn btn-secondary" %>
   </div>
   <% end %>
   </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
<div class="row">
<%= render 'books/list', user: @user, book: @book %>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
          <tr>
            <td>
              <%= attachment_image_tag user, :profile_image, :fill, 40, 40, fallback: "no_image_people.jpg", size: '40x40' %>
            </td>
            <td>
              <%= user.name %>
            </td>
            <td>
              <%= link_to "Show", user_path(user.id) %>
            </td>
            
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
<div class="row">
<%= render  'books/list', user: @user, book: @book %>
<div class="col-md-8 offset-md-1">
  <h2>Books</h2>
    <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
      <tbody>
        <% @books.each do |book| %>
          <% if book.user.id == @user.id %>
            <tr>
              <td>
                <%= link_to user_path(@user.id) do %>
                <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, fallback: "no_image_people.jpg", size: '40x40' %>
                <% end %>
              </td>
              <td>
                <%= link_to book_path(book.id) do %>
                <%= book.title %>
                <% end %>
              </td>
              <td>
                <%= book.body %>
              </td>
              <% if book.favorited_by?(current_user) %>
              <td>
                <%= link_to book_favorites_path(book.id), class:"text-danger fas fa-heart", method: :delete do %>
                  <%= book.favorites.count %>
                <% end %>
              </td>
              <% else %>
              <td>
                <%= link_to book_favorites_path(book.id), class:"fas fa-heart", method: :post do %>
                  <%= book.favorites.count %>
                <% end %>
              </td>
              <% end %>
	    	      <td>コメント数:<%= book.book_comments.count %></td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>